import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
  
export default function HomeLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    );
}
  