import type { Metadata } from "next";
import "../globals.css";
import "@mantine/core/styles.css";
import NavPath from "../components/navpath";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <NavPath/>
        {children}
      </body>
    </html>
  );
}
